name: LeasePlanQATest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Test with Maven
        run: mvn clean test

      - name: Getting Report Ready
        run: |
          mkdir public
          cp target/lp_report.html public/index.html

      - name: Publish Test Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: lease-plan-test/LPTestReport
          publish_branch: main  # default: gh-pages
          publish_dir: ./public